CLASS zcl_lab_23_company_815 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
  GLOBAL FRIENDS zcl_lab_24_partner_815.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
    DATA: capital TYPE string.
ENDCLASS.



CLASS zcl_lab_23_company_815 IMPLEMENTATION.
ENDCLASS.
