CLASS zcl_lab_19_lion_815 DEFINITION
  PUBLIC
  INHERITING FROM zcl_lab_18_animal_815
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS walk REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_19_lion_815 IMPLEMENTATION.
  METHOD walk.
    rv_value = 'El Lion Camina'.
  ENDMETHOD.

ENDCLASS.
