CLASS zcl_lab_21_classroom_815 DEFINITION
  PUBLIC
*  FINAL
  CREATE protected.
*  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_21_CLASSROOM_815 IMPLEMENTATION.
ENDCLASS.
