CLASS zcl_lab_29_organization_815 DEFINITION ABSTRACT
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS:
      get_location ABSTRACT RETURNING VALUE(rv_location) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_29_organization_815 IMPLEMENTATION.
ENDCLASS.
