CLASS zcl_lab_12_linux_815  DEFINITION
INHERITING FROM zcl_lab_11_system_815
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_12_linux_815 IMPLEMENTATION.
ENDCLASS.
